import dynamic from "next/dynamic";
import FroalaEditor from "react-froala-wysiwyg";

dynamic(import("froala-editor/js/froala_editor.min.js"), { ssr: false });
dynamic(import("froala-editor/js/froala_editor.pkgd.min.js"), { ssr: false });
dynamic(import("froala-editor/js/plugins.pkgd.min.js"), { ssr: false });
dynamic(import("froala-editor/js/plugins/lists.min.js"), { ssr: false });
dynamic(import("froala-editor/js/plugins/paragraph_format.min.js"), {
  ssr: false,
});
dynamic(import("froala-editor/js/plugins/paragraph_style.min.js"), {
  ssr: false,
});

// Require Editor CSS files.
import "froala-editor/css/froala_style.min.css";
import "froala-editor/css/froala_editor.pkgd.min.css";

const MyFroalaEditor = () => {
  const froalaConfig = {
    events: {},
    colorsBackground: [
      "#61BD6D",
      "#1ABC9C",
      "#54ACD2",
      "#2C82C9",
      "#9365B8",
      "#475577",
      "#CCCCCC",
      "#41A85F",
      "#00A885",
      "#3D8EB9",
      "#2969B0",
      "#553982",
      "#28324E",
      "#000000",
      "#F7DA64",
      "#FBA026",
      "#EB6B56",
      "#E25041",
      "#A38F84",
      "#EFEFEF",
      "#FFFFFF",
      "#FAC51C",
      "#F37934",
      "#D14841",
      "#B8312F",
      "#7C706B",
      "#D1D5D8",
      "REMOVE",
    ],
    emoticonsSet: [
      {
        code: "1f600",
        desc: "Grinning face",
      },
      {
        code: "1f601",
        desc: "Grinning face with smiling eyes",
      },
      {
        code: "1f602",
        desc: "Face with tears of joy",
      },
      {
        code: "1f603",
        desc: "Smiling face with open mouth",
      },
      {
        code: "1f604",
        desc: "Smiling face with open mouth and smiling eyes",
      },
      {
        code: "1f605",
        desc: "Smiling face with open mouth and cold sweat",
      },
      {
        code: "1f606",
        desc: "Smiling face with open mouth and tightly-closed eyes",
      },
      {
        code: "1f607",
        desc: "Smiling face with halo",
      },
      {
        code: "1f608",
        desc: "Smiling face with horns",
      },
      {
        code: "1f609",
        desc: "Winking face",
      },
      {
        code: "1f60a",
        desc: "Smiling face with smiling eyes",
      },
      {
        code: "1f60b",
        desc: "Face savoring delicious food",
      },
      {
        code: "1f60c",
        desc: "Relieved face",
      },
      {
        code: "1f60d",
        desc: "Smiling face with heart-shaped eyes",
      },
      {
        code: "1f60e",
        desc: "Smiling face with sunglasses",
      },
      {
        code: "1f60f",
        desc: "Smirking face",
      },
      {
        code: "1f610",
        desc: "Neutral face",
      },
      {
        code: "1f611",
        desc: "Expressionless face",
      },
      {
        code: "1f612",
        desc: "Unamused face",
      },
      {
        code: "1f613",
        desc: "Face with cold sweat",
      },
      {
        code: "1f614",
        desc: "Pensive face",
      },
      {
        code: "1f615",
        desc: "Confused face",
      },
      {
        code: "1f616",
        desc: "Confounded face",
      },
      {
        code: "1f617",
        desc: "Kissing face",
      },
      {
        code: "1f618",
        desc: "Face throwing a kiss",
      },
      {
        code: "1f619",
        desc: "Kissing face with smiling eyes",
      },
      {
        code: "1f61a",
        desc: "Kissing face with closed eyes",
      },
      {
        code: "1f61b",
        desc: "Face with stuck out tongue",
      },
      {
        code: "1f61c",
        desc: "Face with stuck out tongue and winking eye",
      },
      {
        code: "1f61d",
        desc: "Face with stuck out tongue and tightly-closed eyes",
      },
      {
        code: "1f61e",
        desc: "Disappointed face",
      },
      {
        code: "1f61f",
        desc: "Worried face",
      },
      {
        code: "1f620",
        desc: "Angry face",
      },
      {
        code: "1f621",
        desc: "Pouting face",
      },
      {
        code: "1f622",
        desc: "Crying face",
      },
      {
        code: "1f623",
        desc: "Persevering face",
      },
      {
        code: "1f624",
        desc: "Face with look of triumph",
      },
      {
        code: "1f625",
        desc: "Disappointed but relieved face",
      },
      {
        code: "1f626",
        desc: "Frowning face with open mouth",
      },
      {
        code: "1f627",
        desc: "Anguished face",
      },
      {
        code: "1f628",
        desc: "Fearful face",
      },
      {
        code: "1f629",
        desc: "Weary face",
      },
      {
        code: "1f62a",
        desc: "Sleepy face",
      },
      {
        code: "1f62b",
        desc: "Tired face",
      },
      {
        code: "1f62c",
        desc: "Grimacing face",
      },
      {
        code: "1f62d",
        desc: "Loudly crying face",
      },
      {
        code: "1f62e",
        desc: "Face with open mouth",
      },
      {
        code: "1f62f",
        desc: "Hushed face",
      },
      {
        code: "1f630",
        desc: "Face with open mouth and cold sweat",
      },
      {
        code: "1f631",
        desc: "Face screaming in fear",
      },
      {
        code: "1f632",
        desc: "Astonished face",
      },
      {
        code: "1f633",
        desc: "Flushed face",
      },
      {
        code: "1f634",
        desc: "Sleeping face",
      },
      {
        code: "1f635",
        desc: "Dizzy face",
      },
      {
        code: "1f636",
        desc: "Face without mouth",
      },
      {
        code: "1f637",
        desc: "Face with medical mask",
      },
    ],
    embedlyEditButtons: ["embedlyRemove"],
    fontSizeSelection: true,
    fontFamily: {
      "Arial,Helvetica,sans-serif": "Arial",
      "Georgia,serif": "Georgia",
      "Impact,Charcoal,sans-serif": "Impact",
      "Tahoma,Geneva,sans-serif": "Tahoma",
      "Times New Roman,Times,serif": "Times New Roman",
      "Verdana,Geneva,sans-serif": "Verdana",
    },
    fileAllowedTypes: ["*"],
    fileInsertButtons: ["fileBack", "|"],
    fileMaxSize: 1024,
    fileUpload: false,
    fileUploadMethod: "POST",
    fileUploadParam: "file",
    fileUploadToS3: false,
    fileUploadParams: {},
    fileUploadURL: "http://i.froala.com/upload",
    fileUseSelectedText: true,
    lineBreakerHorizontalOffset: 10,
    lineBreakerOffset: 15,
    lineBreakerTags: [
      "table",
      "hr",
      "form",
      "dl",
      "span.fr-video",
      ".fr-embedly",
      ".fr-img-caption",
    ],
    imageManagerDeleteMethod: "POST",
    imageManagerDeleteParams: {},
    imageManagerLoadMethod: "GET",
    imageManagerDeleteURL: "",
    imageManagerLoadParams: {},
    imageManagerLoadURL: "http://i.froala.com/load-files",
    imageManagerPageSize: 12,
    imageManagerPreloader: "",
    imageAllowedTypes: ["jpeg", "jpg", "png", "gif", "webp"],
    imageAltButtons: ["imageBack", "|"],
    imageDefaultAlign: "center",
    imageCORSProxy: "https://cors-anywhere.froala.com",
    imageDefaultDisplay: "block",
    imageDefaultMargin: 5,
    imageDefaultWidth: 300,
    imageEditButtons: [
      "imageReplace",
      "imageAlign",
      "imageCaption",
      "imageRemove",
      "|",
      "imageLink",
      "linkOpen",
      "linkEdit",
      "linkRemove",
      "-",
      "imageDisplay",
      "imageStyle",
      "imageAlt",
      "imageSize",
    ],
    imageMaxSize: 1024,
    imageInsertButtons: [
      "imageBack",
      "|",
      "imageUpload",
      "imageByURL",
      "imageManager",
    ],
    imageMinWidth: 16,
    imageMove: false,
    imageMultipleStyles: false,
    imagePaste: false,
    imageResize: false,
    imagePasteProcess: true,
    imageResizeWithPercent: true,
    imageRoundPercent: true,
    imageSizeButtons: ["imageBack", "|"],
    imageOutputSize: true,
    imageSplitHTML: true,
    imageStyles: {
      "fr-rounded": "Rounded",
      "fr-bordered": "Bordered",
    },
    imageTextNear: false,
    imageTUIOptions: {
      includeUI: {
        initMenu: "filter",
        menuBarPosition: "left",
        theme: {
          "menu.activeIcon.path":
            "https://cdn.jsdelivr.net/npm/tui-image-editor@3.2.2/dist/svg/icon-b.svg",
          "menu.disabledIcon.path":
            "https://cdn.jsdelivr.net/npm/tui-image-editor@3.2.2/dist/svg/icon-a.svg",
          "menu.hoverIcon.path":
            "https://cdn.jsdelivr.net/npm/tui-image-editor@3.2.2/dist/svg/icon-c.svg",
          "menu.normalIcon.path":
            "https://cdn.jsdelivr.net/npm/tui-image-editor@3.2.2/dist/svg/icon-d.svg",
          "submenu.activeIcon.name": "icon-c",
          "submenu.activeIcon.path":
            "https://cdn.jsdelivr.net/npm/tui-image-editor@3.2.2/dist/svg/icon-c.svg",
          "submenu.normalIcon.name": "icon-d",
          "submenu.normalIcon.path":
            "https://cdn.jsdelivr.net/npm/tui-image-editor@3.2.2/dist/svg/icon-d.svg",
        },
      },
    },
    imageUpload: false,
    imageAddNewLine: true,
    imageUploadParam: "file",
    imageUploadMethod: "POST",
    imageUploadParams: {},
    imageUploadRemoteUrls: false,
    imageUploadToS3: false,
    imageUploadURL: null,
    specialCharButtons: ["specialCharBack", "|"],
    specialCharactersSets: {},
    quickInsertButtons: [
      "image",
      "video",
      "embedly",
      "table",
      "ul",
      "ol",
      "hr",
    ],
    quickInsertEnabled: false,
    quickInsertTags: [
      "p",
      "div",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "pre",
      "blockquote",
    ],
    paragraphDefaultSelection: "Paragraph Format",
    paragraphFormat: {
      N: "Normal",
      H1: "Heading 1",
      H2: "Heading 2",
      H3: "Heading 3",
      H4: "Heading 4",
      PRE: "Code",
    },
    paragraphFormatSelection: true,
    paragraphMultipleStyles: false,
    lineHeights: {
      Default: "",
      Single: "1",
      1.15: "1.15",
      1.5: "1.5",
      Double: "2",
    },
    paragraphStyles: {
      "fr-text-gray": "Gray",
      "fr-text-bordered": "Bordered",
      "fr-text-spaced": "Spaced",
      "fr-text-uppercase": "Uppercase",
    },
    linkAlwaysBlank: true,
    linkAlwaysNoFollow: false,
    linkAutoPrefix: "http://",
    linkAttributes: {},
    linkConvertEmailAddress: false,
    linkEditButtons: ["linkOpen", "linkStyle", "linkEdit", "linkRemove"],
    linkInsertButtons: ["linkBack", "|", "linkList"],
    linkList: [],
    linkMultipleStyles: false,
    linkNoOpener: false,
    linkNoReferrer: false,
    linkStyles: {
      "fr-green": "Green",
      "fr-strong": "Thick",
    },
    linkText: true,
    listAdvancedTypes: false,
    faButtons: ["fontAwesomeBack", "|"],
    fontAwesomeSets: {},
    saveInterval: 10000,
    saveMethod: "POST",
    saveParam: "body",
    saveParams: {},
    saveURL: null,
    videoAllowedProviders: [".*"],
    videoAllowedTypes: ["mp4", "webm", "ogg"],
    videoDefaultAlign: "center",
    videoDefaultDisplay: "block",
    tableCellMultipleStyles: false,
    tableColorsButtons: ["tableBack", "|"],
    tableColors: [
      "#61BD6D",
      "#1ABC9C",
      "#54ACD2",
      "#2C82C9",
      "#9365B8",
      "#475577",
      "#CCCCCC",
      "#41A85F",
      "#00A885",
      "#3D8EB9",
      "#2969B0",
      "#553982",
      "#28324E",
      "#000000",
      "#F7DA64",
      "#FBA026",
      "#EB6B56",
      "#E25041",
      "#A38F84",
      "#EFEFEF",
      "#FFFFFF",
      "#FAC51C",
      "#F37934",
      "#D14841",
      "#B8312F",
      "#7C706B",
      "#D1D5D8",
      "REMOVE",
    ],
    tableColorsStep: 7,
    tableDefaultWidth: "100%",
    tableEditButtons: [
      "tableHeader",
      "tableRemove",
      "|",
      "tableRows",
      "tableColumns",
      "tableStyle",
      "-",
      "tableCells",
      "tableCellBackground",
      "tableCellVerticalAlign",
      "tableCellHorizontalAlign",
      "tableCellStyle",
    ],
    tableInsertButtons: ["tableBack", "|"],
    tableInsertHelper: false,
    tableInsertHelperOffset: 15,
    tableInsertMaxSize: 10,
    tableMultipleStyles: false,
    tableResizer: false,
    tableResizerOffset: 5,
    tableResizingLimit: 30,
    tableStyles: {
      "fr-dashed-borders": "Dashed Borders",
      "fr-alternate-rows": "Alternate Rows",
    },
    videoDefaultWidth: 600,
    videoEditButtons: [
      "videoReplace",
      "videoRemove",
      "|",
      "videoDisplay",
      "videoAlign",
      "videoSize",
    ],
    videoMaxSize: 1024,
    videoInsertButtons: [
      "videoBack",
      "|",
      "videoByURL",
      "videoEmbed",
      "videoUpload",
    ],
    videoMove: false,
    videoResize: false,
    videoResponsive: true,
    videoSizeButtons: ["videoBack", "|"],
    videoTextNear: false,
    videoSplitHTML: true,
    videoUpload: false,
    videoUploadMethod: "POST",
    videoUploadParams: {},
    videoUploadParam: "file",
    videoUploadToS3: false,
    videoUploadURL: null,
    wordAllowedStyleProps: [
      "font-family",
      "font-size",
      "background",
      "color",
      "width",
      "text-align",
      "vertical-align",
      "background-color",
      "padding",
      "margin",
      "height",
      "margin-top",
      "margin-left",
      "margin-right",
      "margin-bottom",
      "text-decoration",
      "font-weight",
      "font-style",
      "text-indent",
      "border",
      "border-.*",
    ],
    wordDeniedAttrs: [],
    wordPasteModal: false,
    wordDeniedTags: [],
    wordPasteKeepFormatting: false,
    filesManagerAllowedTypes: ["*"],
    filesManagerMaxSize: 1024,
    filesManagerUploadParams: {},
    filesManagerUploadToS3: false,
    filesManagerUploadURL: "http://i.froala.com/upload",
    language: "en_ca",
  };

  return <FroalaEditor tag="textarea" />;
};

export default MyFroalaEditor;
